# Generated by Django 4.2.24 on 2025-09-23 21:45

from django.db import migrations, models
import vidapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=vidapp.models.user_directory_path)),
                ('ipload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
