# Generated by Django 4.2.24 on 2025-09-24 01:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vidapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('youtube_url', models.URLField()),
                ('youtube_id', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('channel_title', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('source_video', models.FileField(blank=True, upload_to=vidapp.models.user_directory_path)),
                ('wav_audio', models.FileField(blank=True, upload_to=vidapp.models.user_directory_path)),
                ('transcript_json', models.FileField(blank=True, upload_to=vidapp.models.user_directory_path)),
                ('transcript_vtt', models.FileField(blank=True, upload_to=vidapp.models.user_directory_path)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('segment_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('failed', 'Failed'), ('awaiting_transcription', 'Awaiting_transcription')], default='queued', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('failed', 'Failed'), ('awaiting_transcription', 'Awaiting_transcription')], default='queued', max_length=32)),
                ('percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('message', models.CharField(blank=True, max_length=300)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RM',
        ),
    ]
